"""``project`` table — customer project / workspace container."""

from datetime import (
    UTC,
    datetime,
)
from typing import Optional
from uuid import UUID

from sqlmodel import Field, SQLModel


class Project(SQLModel, table=True):
    """A named project workspace (e.g. 'Acme Prod').

    Attributes:
        id: UUID primary key; generated by the database.
        name: Human-readable project name.
        description: Optional longer description.
        created_at: Row creation timestamp (UTC).
        updated_at: Last modification timestamp (UTC); auto-updated by DB trigger.
    """

    __tablename__ = "project"  # type: ignore[assignment]

    id: Optional[UUID] = Field(default=None, primary_key=True)
    name: str
    description: Optional[str] = Field(default=None)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
