"""``project`` table — customer project / workspace container."""

from datetime import (
    UTC,
    datetime,
)
from typing import (
    TYPE_CHECKING,
    Optional,
)
from uuid import (
    UUID,
    uuid4,
)

from sqlmodel import (
    Field,
    Relationship,
    SQLModel,
    UniqueConstraint,
)

if TYPE_CHECKING:
    from app.models.user import User


class Project(SQLModel, table=True):
    """A named project workspace (e.g. 'Acme Prod') scoped to one user.

    Attributes:
        id: UUID primary key; generated by the database.
        user_id: FK to the owning user account.
        name: Human-readable project name (unique per user).
        description: Optional longer description.
        created_at: Row creation timestamp (UTC).
        updated_at: Last modification timestamp (UTC); auto-updated by DB trigger.
    """

    __tablename__ = "project"  # type: ignore[assignment]
    __table_args__ = (UniqueConstraint("user_id", "name", name="uq_project_user_name"),)

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: int = Field(foreign_key="user.id", index=True)
    name: str
    description: Optional[str] = Field(default=None)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    user: "User" = Relationship()
