"""Seed canonical_field table.

Revision ID: a1b2c3d4e5f6
Revises: b25d38b0cd7c
Create Date: 2026-06-10

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text as sa_text

revision: str = "a1b2c3d4e5f6"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "b25d38b0cd7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


CANONICAL_FIELDS = [
    # ------------------------------------------------------------------ #
    # user.pii  →  category = 'identity', is_pii = true
    # ------------------------------------------------------------------ #
    (
        "user.pii.first_name",
        "First Name",
        "Customer's first name, used for identity matching and personalisation.",
        "identity",
        True,
    ),
    (
        "user.pii.first_name_initial",
        "First Name Initial",
        "First initial of the customer's first name, used as a lightweight identity signal.",
        "identity",
        True,
    ),
    (
        "user.pii.last_name",
        "Last Name",
        "Customer's last name, used for identity matching.",
        "identity",
        True,
    ),
    (
        "user.pii.middle_name",
        "Middle Name",
        "Customer's middle name, used as a supplementary identity signal.",
        "identity",
        True,
    ),
    (
        "user.pii.full_name",
        "Full Name",
        "Customer's full name as a single string, used for identity matching.",
        "identity",
        True,
    ),
    (
        "user.pii.phone",
        "Phone",
        "Customer's phone number in raw (unhashed) form.",
        "identity",
        True,
    ),
    (
        "user.pii.phone_hashed",
        "Phone Hashed",
        "Customer's primary phone number, hashed per destination spec.",
        "identity",
        True,
    ),
    (
        "user.pii.phone_1_hashed_format_a",
        "Phone 1 Hashed Format A",
        "Primary phone number hashed in format A (e.g. E.164 without country code).",
        "identity",
        True,
    ),
    (
        "user.pii.phone_1_hashed_format_b",
        "Phone 1 Hashed Format B",
        "Primary phone number hashed in format B (e.g. with country code prefix).",
        "identity",
        True,
    ),
    (
        "user.pii.phone_2_hashed_format_a",
        "Phone 2 Hashed Format A",
        "Secondary phone number hashed in format A.",
        "identity",
        True,
    ),
    (
        "user.pii.phone_2_hashed_format_b",
        "Phone 2 Hashed Format B",
        "Secondary phone number hashed in format B.",
        "identity",
        True,
    ),
    (
        "user.pii.phone_3_hashed_format_a",
        "Phone 3 Hashed Format A",
        "Tertiary phone number hashed in format A.",
        "identity",
        True,
    ),
    (
        "user.pii.phone_3_hashed_format_b",
        "Phone 3 Hashed Format B",
        "Tertiary phone number hashed in format B.",
        "identity",
        True,
    ),
    (
        "user.pii.email_hashed",
        "Email Hashed",
        "Customer's primary email address, hashed per destination spec (SHA-256 lowercase).",
        "identity",
        True,
    ),
    (
        "user.pii.email_1_hashed",
        "Email 1 Hashed",
        "Customer's primary email address hashed — used when multi-email slots are supported.",
        "identity",
        True,
    ),
    (
        "user.pii.email_2_hashed",
        "Email 2 Hashed",
        "Customer's secondary email address, hashed.",
        "identity",
        True,
    ),
    (
        "user.pii.email_3_hashed",
        "Email 3 Hashed",
        "Customer's tertiary email address, hashed.",
        "identity",
        True,
    ),
    (
        "user.pii.gender",
        "Gender",
        "Customer's gender in raw form.",
        "identity",
        True,
    ),
    (
        "user.pii.gender_hashed",
        "Gender Hashed",
        "Customer's gender, hashed per destination spec.",
        "identity",
        True,
    ),
    (
        "user.pii.date_of_birth",
        "Date Of Birth",
        "Customer's full date of birth in raw form.",
        "identity",
        True,
    ),
    (
        "user.pii.date_of_birth_hashed",
        "Date Of Birth Hashed",
        "Customer's full date of birth, hashed.",
        "identity",
        True,
    ),
    (
        "user.pii.date_of_birth_whole",
        "Date Of Birth Whole",
        "Customer's complete date of birth as a single value (raw).",
        "identity",
        True,
    ),
    (
        "user.pii.doby",
        "Doby",
        "Customer's year of birth (raw). Alternative canonical form — see also dob_year_hash.",
        "identity",
        True,
    ),
    (
        "user.pii.dobm",
        "Dobm",
        "Customer's month of birth (raw). Alternative canonical form — see also dob_month_hash.",
        "identity",
        True,
    ),
    (
        "user.pii.dobd",
        "Dobd",
        "Customer's day of birth (raw). Alternative canonical form — see also dob_day_hash.",
        "identity",
        True,
    ),
    (
        "user.pii.dob_year_hash",
        "Dob Year Hash",
        "Customer's year of birth, hashed.",
        "identity",
        True,
    ),
    (
        "user.pii.dob_month_hash",
        "Dob Month Hash",
        "Customer's month of birth, hashed.",
        "identity",
        True,
    ),
    (
        "user.pii.dob_day_hash",
        "Dob Day Hash",
        "Customer's day of birth, hashed.",
        "identity",
        True,
    ),
    (
        "user.pii.city_hashed",
        "City Hashed",
        "Customer's city, hashed per destination spec.",
        "identity",
        True,
    ),
    (
        "user.pii.state",
        "State",
        "Customer's state or region in raw form.",
        "identity",
        True,
    ),
    (
        "user.pii.state_hashed",
        "State Hashed",
        "Customer's state or region, hashed per destination spec.",
        "identity",
        True,
    ),
    (
        "user.pii.zipcode",
        "Zipcode",
        "Customer's postal / ZIP code in raw form.",
        "identity",
        True,
    ),
    (
        "user.pii.zipcode_hashed",
        "Zipcode Hashed",
        "Customer's postal / ZIP code, hashed per destination spec.",
        "identity",
        True,
    ),
    (
        "user.pii.country",
        "Country",
        "Customer's country in raw form (ISO 3166-1 alpha-2 recommended).",
        "identity",
        True,
    ),
    (
        "user.pii.country_hashed",
        "Country Hashed",
        "Customer's country, hashed per destination spec.",
        "identity",
        True,
    ),
    (
        "user.pii.external_id",
        "External Id",
        "Advertiser-assigned external identifier for the customer (e.g. CRM ID).",
        "identity",
        True,
    ),
    (
        "user.pii.mobile_ad_id",
        "Mobile Ad Id",
        "Mobile advertising ID (IDFA / GAID), hashed per destination spec.",
        "identity",
        True,
    ),
    (
        "user.pii.mobile_advertiser_id",
        "Mobile Advertiser Id",
        "Raw mobile advertiser ID before hashing.",
        "identity",
        True,
    ),
    (
        "user.pii.language_code",
        "Language Code",
        "Customer's preferred language (BCP-47 code, e.g. en-US).",
        "identity",
        True,
    ),
    (
        "user.pii.merchant_feed_label",
        "Merchant Feed Label",
        "Label identifying the merchant product feed associated with this customer record.",
        "identity",
        True,
    ),
    (
        "user.pii.merchant_feed_language_code",
        "Merchant Feed Language Code",
        "Language code for the merchant product feed.",
        "identity",
        True,
    ),
    (
        "user.pii.transaction_discount",
        "Transaction Discount",
        "Discount applied to the transaction, used in cart-level reporting.",
        "identity",
        True,
    ),
    (
        "user.pii.session_attributes",
        "Session Attributes",
        "Session-level attributes passed to Google Ads for enhanced match (destination-specific).",
        "identity",
        True,
    ),
    # ------------------------------------------------------------------ #
    # user.general  →  category = 'identity', is_pii = false
    # ------------------------------------------------------------------ #
    (
        "user.general.client_ip_address",
        "Client Ip Address",
        "IP address of the client device at the time of the event, used for signal enrichment.",
        "identity",
        False,
    ),
    (
        "user.general.client_user_agent",
        "Client User Agent",
        "User-agent string of the client browser or app, used for device-level matching.",
        "identity",
        False,
    ),
    (
        "user.general.browser_id",
        "Browser Id",
        "Browser-level identifier (e.g. Facebook _fbp cookie) for probabilistic matching.",
        "identity",
        False,
    ),
    (
        "user.general.click_id",
        "Click Id",
        "Generic click identifier from the ad platform (non-Facebook). See platform-specific variants for fb.click_id, gclid, etc.",
        "identity",
        False,
    ),
    (
        "user.general.gclid",
        "Gclid",
        "Google Click ID — links the conversion back to the originating Google Ads click. Google-specific.",
        "identity",
        False,
    ),
    (
        "user.general.gbraid",
        "Gbraid",
        "Google BRAID identifier for app conversions measured with SKAdNetwork. Google-specific.",
        "identity",
        False,
    ),
    (
        "user.general.wbraid",
        "Wbraid",
        "Google WBRAID identifier for web conversions from app campaigns. Google-specific.",
        "identity",
        False,
    ),
    (
        "user.general.fbc",
        "Fbc",
        "Facebook click ID cookie (_fbc), used for Meta Conversions API event attribution.",
        "identity",
        False,
    ),
    (
        "user.general.external_id",
        "External Id",
        "Non-PII external identifier for the user (e.g. anonymised CRM key).",
        "identity",
        False,
    ),
    (
        "user.general.idfa",
        "Idfa",
        "Apple IDFA (Identifier for Advertisers), used for mobile attribution.",
        "identity",
        False,
    ),
    (
        "user.general.facebook_app_user_id",
        "Facebook App User Id",
        "Facebook App-Scoped User ID, used for Meta app event matching.",
        "identity",
        False,
    ),
    (
        "user.general.facebook_page_user_id",
        "Facebook Page User Id",
        "Facebook Page-Scoped User ID, used for Meta page event matching.",
        "identity",
        False,
    ),
    (
        "user.general.fb.lead_id_fb",
        "Lead Id Fb",
        "Facebook Lead Ad lead ID, used to match a lead form submission to a Meta user.",
        "identity",
        False,
    ),
    (
        "user.general.fb.click_id",
        "Click Id",
        "Facebook click ID (_fbc value). Alternative path — see also user.general.fbc.",
        "identity",
        False,
    ),
    (
        "user.general.fb.fb_login_id_fb",
        "Fb Login Id Fb",
        "Facebook Login ID, used for matching users authenticated via Facebook Login.",
        "identity",
        False,
    ),
    (
        "user.general.fb.subscription_id_fb",
        "Subscription Id Fb",
        "Facebook subscription identifier, used for recurring payment event matching.",
        "identity",
        False,
    ),
    (
        "user.general.fb_login_id",
        "Fb Login Id",
        "Facebook Login ID (alternate canonical path). See also user.general.fb.fb_login_id_fb.",
        "identity",
        False,
    ),
    (
        "user.general.tiktok.lead_id",
        "Lead Id",
        "TikTok Lead Ad lead ID, used to match a lead form submission to a TikTok user.",
        "identity",
        False,
    ),
    (
        "user.general.snapchat.lead_id",
        "Lead Id",
        "Snapchat Lead Ad lead ID, used to match a lead form submission to a Snapchat user.",
        "identity",
        False,
    ),
    (
        "user.general.linkedin.lead_id",
        "Lead Id",
        "LinkedIn Lead Gen Form lead ID, used to match a submission to a LinkedIn member.",
        "identity",
        False,
    ),
    # ------------------------------------------------------------------ #
    # event.general  →  category = 'event', is_pii = false
    # ------------------------------------------------------------------ #
    (
        "event.general.event_id",
        "Event Id",
        "Unique identifier for the event, used for deduplication across sources and destinations.",
        "event",
        False,
    ),
    (
        "event.general.event_name",
        "Event Name",
        "Standardised event name (e.g. Purchase, Lead, ViewContent) sent to the destination.",
        "event",
        False,
    ),
    (
        "event.general.event_time",
        "Event Time",
        "Unix timestamp (seconds) of when the event occurred.",
        "event",
        False,
    ),
    (
        "event.general.event_source_url",
        "Event Source Url",
        "URL of the page where the event occurred, used for web event attribution.",
        "event",
        False,
    ),
    (
        "event.general.event_tag",
        "Event Tag",
        "Platform-specific tag or label associated with the event.",
        "event",
        False,
    ),
    (
        "event.general.action_source",
        "Action Source",
        "Where the conversion action took place (e.g. website, app, crm, email).",
        "event",
        False,
    ),
    (
        "event.general.lead_event_source",
        "Lead Event Source",
        "The source platform that generated the lead event (e.g. Facebook Lead Ads).",
        "event",
        False,
    ),
    (
        "event.general.last_modified_date",
        "Last Modified Date",
        "Timestamp when the source record was last modified, used for incremental sync detection.",
        "event",
        False,
    ),
    (
        "event.general.transaction_id",
        "Transaction Id",
        "Unique identifier for the transaction or order, used for deduplication and reporting.",
        "event",
        False,
    ),
    (
        "event.general.content_value",
        "Content Value",
        "Monetary value of the conversion event (e.g. order total). Sent as a float.",
        "event",
        False,
    ),
    (
        "event.general.content_ids",
        "Content Ids",
        "List of product or content IDs associated with the event (e.g. for cart events).",
        "event",
        False,
    ),
    (
        "event.general.content_type",
        "Content Type",
        "Type of content or product involved in the event (e.g. product, product_group).",
        "event",
        False,
    ),
    (
        "event.general.content_name",
        "Content Name",
        "Name of the product or content associated with the event.",
        "event",
        False,
    ),
    (
        "event.general.content_category",
        "Content Category",
        "Category of the product or content associated with the event.",
        "event",
        False,
    ),
    (
        "event.general.delivery_category",
        "Delivery Category",
        "How the order was delivered (e.g. home_delivery, in_store, curbside).",
        "event",
        False,
    ),
    (
        "event.general.delivery_method",
        "Delivery Method",
        "Delivery method for the order, used for fulfilment-level reporting.",
        "event",
        False,
    ),
    (
        "event.general.number_items",
        "Number Items",
        "Total number of items in the cart or order.",
        "event",
        False,
    ),
    (
        "event.general.item_number",
        "Item Number",
        "Line-item number within the order, used for itemised conversion reporting.",
        "event",
        False,
    ),
    (
        "event.general.predicted_ltv",
        "Predicted Ltv",
        "Predicted lifetime value of the customer, used for value-based bidding optimisation.",
        "event",
        False,
    ),
    (
        "event.general.status",
        "Status",
        "Status of the event or order (e.g. completed, pending, cancelled).",
        "event",
        False,
    ),
    (
        "event.general.search_string",
        "Search String",
        "Search query string entered by the user, used for Search conversion events.",
        "event",
        False,
    ),
    (
        "event.general.shop_id",
        "Shop Id",
        "Identifier of the shop or store associated with the event.",
        "event",
        False,
    ),
    (
        "event.general.subscription_id",
        "Subscription Id",
        "Identifier of the subscription associated with the event.",
        "event",
        False,
    ),
    (
        "event.general.customer_status",
        "Customer Status",
        "Customer's lifecycle status at the time of the event (e.g. new, returning).",
        "event",
        False,
    ),
    (
        "event.general.product_group_id",
        "Product Group Id",
        "Identifier of the product group, used for catalogue-level reporting.",
        "event",
        False,
    ),
    (
        "event.general.custom_key_1",
        "Custom Key 1",
        "Custom attribute key slot 1 — for destination-specific or advertiser-defined fields.",
        "event",
        False,
    ),
    (
        "event.general.custom_value_1",
        "Custom Value 1",
        "Custom attribute value slot 1 — paired with custom_key_1.",
        "event",
        False,
    ),
    (
        "event.general.contents",
        "Contents",
        "Array of product/content objects in the event (id, quantity, price, etc.).",
        "event",
        False,
    ),
    (
        "event.general.contents.id",
        "Id",
        "Product or content ID within a contents array item.",
        "event",
        False,
    ),
    (
        "event.general.contents.title",
        "Title",
        "Product or content title within a contents array item.",
        "event",
        False,
    ),
    (
        "event.general.contents.brand",
        "Brand",
        "Brand name of the product within a contents array item.",
        "event",
        False,
    ),
    (
        "event.general.contents.item_price",
        "Item Price",
        "Unit price of the product within a contents array item.",
        "event",
        False,
    ),
    (
        "event.general.contents.quantity",
        "Quantity",
        "Quantity of the product within a contents array item.",
        "event",
        False,
    ),
    (
        "event.general.contents.order_id",
        "Order Id",
        "Order identifier within a contents array item, for order-level deduplication.",
        "event",
        False,
    ),
    # ------------------------------------------------------------------ #
    # event.monetary  →  category = 'monetary', is_pii = false
    # ------------------------------------------------------------------ #
    (
        "event.monetary.currency",
        "Currency",
        "ISO 4217 currency code for the conversion value (e.g. USD, EUR, INR).",
        "monetary",
        False,
    ),
    # ------------------------------------------------------------------ #
    # product.*  →  category = 'product', is_pii = false
    # ------------------------------------------------------------------ #
    ("product.id", "Id", "Unique product identifier in the merchant catalogue.", "product", False),
    ("product.name", "Name", "Display name of the product.", "product", False),
    ("product.description", "Description", "Full product description.", "product", False),
    ("product.link", "Link", "Canonical URL of the product page.", "product", False),
    ("product.image_main", "Image Main", "URL of the primary product image.", "product", False),
    ("product.image_others", "Image Others", "URLs of additional product images.", "product", False),
    ("product.lifestyle_images", "Lifestyle Images", "URLs of lifestyle/contextual product images.", "product", False),
    ("product.language", "Language", "Language of the product listing (BCP-47).", "product", False),
    ("product.country", "Country", "Target country for the product listing (ISO 3166-1 alpha-2).", "product", False),
    ("product.feed_label", "Feed Label", "Label identifying the product feed this item belongs to.", "product", False),
    ("product.channel", "Channel", "Distribution channel for the product (e.g. online, local).", "product", False),
    ("product.brand", "Brand", "Brand name of the product.", "product", False),
    ("product.colour", "Colour", "Colour of the product.", "product", False),
    ("product.category_google", "Category Google", "Google product category taxonomy ID or path.", "product", False),
    ("product.gtin", "Gtin", "Global Trade Item Number (barcode) of the product.", "product", False),
    ("product.group_id", "Group Id", "Product group identifier for variants.", "product", False),
    ("product.material", "Material", "Primary material the product is made of.", "product", False),
    ("product.mpn", "Mpn", "Manufacturer Part Number.", "product", False),
    ("product.pattern", "Pattern", "Pattern or graphic print of the product.", "product", False),
    ("product.price", "Price", "Regular selling price of the product.", "product", False),
    ("product.currency", "Currency", "Currency of the product price (ISO 4217).", "product", False),
    ("product.sale_price", "Sale Price", "Discounted sale price of the product.", "product", False),
    ("product.sale_price_currency", "Sale Price Currency", "Currency of the sale price.", "product", False),
    (
        "product.sale_price_start_date",
        "Sale Price Start Date",
        "Start date of the sale price window.",
        "product",
        False,
    ),
    ("product.sale_price_end_date", "Sale Price End Date", "End date of the sale price window.", "product", False),
    ("product.height", "Height", "Height of the product.", "product", False),
    ("product.length", "Length", "Length of the product.", "product", False),
    ("product.width", "Width", "Width of the product.", "product", False),
    ("product.weight", "Weight", "Weight of the product.", "product", False),
    ("product.dimension_unit", "Dimension Unit", "Unit for product dimensions (e.g. cm, in).", "product", False),
    (
        "product.shipping_weight",
        "Shipping Weight",
        "Weight of the product when packaged for shipping.",
        "product",
        False,
    ),
    ("product.shipping_weight_unit", "Shipping Weight Unit", "Unit for shipping weight.", "product", False),
    ("product.shipping_length", "Shipping Length", "Length of the packaged product.", "product", False),
    ("product.shipping_length_unit", "Shipping Length Unit", "Unit for shipping length.", "product", False),
    ("product.shipping_width", "Shipping Width", "Width of the packaged product.", "product", False),
    ("product.shipping_width_unit", "Shipping Width Unit", "Unit for shipping width.", "product", False),
    ("product.shipping_height", "Shipping Height", "Height of the packaged product.", "product", False),
    ("product.shipping_height_unit", "Shipping Height Unit", "Unit for shipping height.", "product", False),
    ("product.shipping_country", "Shipping Country", "Country to which this shipping rule applies.", "product", False),
    ("product.shipping_region", "Shipping Region", "Region to which this shipping rule applies.", "product", False),
    ("product.shipping_cost", "Shipping Cost", "Fixed shipping cost for this product.", "product", False),
    ("product.shipping_currency", "Shipping Currency", "Currency of the shipping cost.", "product", False),
    (
        "product.shipping_service",
        "Shipping Service",
        "Shipping service level (e.g. Standard, Express).",
        "product",
        False,
    ),
    (
        "product.shipping_location_id",
        "Shipping Location Id",
        "Location ID to which this shipping rule applies.",
        "product",
        False,
    ),
    (
        "product.shipping_location_group_name",
        "Shipping Location Group Name",
        "Named location group for the shipping rule.",
        "product",
        False,
    ),
    (
        "product.shipping_postal_code",
        "Shipping Postal Code",
        "Postal code range for the shipping rule.",
        "product",
        False,
    ),
    (
        "product.shipping_min_handling_time",
        "Shipping Min Handling Time",
        "Minimum handling time before dispatch (days).",
        "product",
        False,
    ),
    (
        "product.shipping_max_handling_time",
        "Shipping Max Handling Time",
        "Maximum handling time before dispatch (days).",
        "product",
        False,
    ),
    (
        "product.shipping_min_transit_time",
        "Shipping Min Transit Time",
        "Minimum transit time after dispatch (days).",
        "product",
        False,
    ),
    (
        "product.shipping_max_transit_time",
        "Shipping Max Transit Time",
        "Maximum transit time after dispatch (days).",
        "product",
        False,
    ),
    (
        "product.shipping_label",
        "Shipping Label",
        "Custom label for grouping products with the same shipping rules.",
        "product",
        False,
    ),
    (
        "product.identifier_exists",
        "Identifier Exists",
        "Whether a unique product identifier (GTIN/MPN/brand) exists.",
        "product",
        False,
    ),
    (
        "product.installment_months",
        "Installment Months",
        "Number of months for the installment payment plan.",
        "product",
        False,
    ),
    ("product.installment_amount", "Installment Amount", "Monthly installment amount.", "product", False),
    (
        "product.installment_amount_currency",
        "Installment Amount Currency",
        "Currency of the installment amount.",
        "product",
        False,
    ),
    ("product.loyalty_points_name", "Loyalty Points Name", "Name of the loyalty points programme.", "product", False),
    (
        "product.loyalty_points",
        "Loyalty Points",
        "Number of loyalty points awarded for this product.",
        "product",
        False,
    ),
    (
        "product.loyalty_points_ratio",
        "Loyalty Points Ratio",
        "Ratio of loyalty points to currency value.",
        "product",
        False,
    ),
    ("product.multipack", "Multipack", "Number of identical products sold as a multipack.", "product", False),
    ("product.bundle", "Bundle", "Whether the product is a bundle of different items.", "product", False),
    ("product.mobile_link", "Mobile Link", "Mobile-optimised URL of the product page.", "product", False),
    (
        "product.mobile_link_template",
        "Mobile Link Template",
        "URL template for mobile product links with ValueTrack parameters.",
        "product",
        False,
    ),
    (
        "product.link_template",
        "Link Template",
        "URL template for product links with ValueTrack parameters.",
        "product",
        False,
    ),
    (
        "product.availability",
        "Availability",
        "Product availability status (e.g. in_stock, out_of_stock, preorder).",
        "product",
        False,
    ),
    (
        "product.availability_date",
        "Availability Date",
        "Date when a preordered/backordered product becomes available.",
        "product",
        False,
    ),
    ("product.expiration_date", "Expiration Date", "Date when the product listing expires.", "product", False),
    (
        "product.expiration_date_google",
        "Expiration Date Google",
        "Google-specific expiration date for the product listing.",
        "product",
        False,
    ),
    (
        "product.disclosure_date_google",
        "Disclosure Date Google",
        "Google-specific date the product was first publicly disclosed.",
        "product",
        False,
    ),
    ("product.adult", "Adult", "Whether the product is intended for adults only.", "product", False),
    (
        "product.age_group",
        "Age Group",
        "Target age group for the product (e.g. adult, kids, infant).",
        "product",
        False,
    ),
    ("product.gender", "Gender", "Target gender for the product (e.g. male, female, unisex).", "product", False),
    ("product.condition", "Condition", "Condition of the product (e.g. new, refurbished, used).", "product", False),
    ("product.size_system", "Size System", "Sizing system used (e.g. US, EU, UK).", "product", False),
    (
        "product.size_type",
        "Size Type",
        "Size type of the product (e.g. regular, petite, maternity).",
        "product",
        False,
    ),
    ("product.additional_size_type", "Additional Size Type", "Additional size type information.", "product", False),
    ("product.sizes", "Sizes", "Available sizes for the product.", "product", False),
    (
        "product.energy_efficiency_class",
        "Energy Efficiency Class",
        "EU energy efficiency rating (e.g. A+++).",
        "product",
        False,
    ),
    (
        "product.min_energy_efficiency_class",
        "Min Energy Efficiency Class",
        "Minimum energy efficiency class in the displayed range.",
        "product",
        False,
    ),
    (
        "product.max_energy_efficiency",
        "Max Energy Efficiency",
        "Maximum energy efficiency class in the displayed range.",
        "product",
        False,
    ),
    ("product.tax_category", "Tax Category", "Tax category for the product.", "product", False),
    ("product.tax_rate", "Tax Rate", "Tax rate applicable to the product.", "product", False),
    ("product.tax_country", "Tax Country", "Country for which the tax rule applies.", "product", False),
    ("product.tax_region", "Tax Region", "Region for which the tax rule applies.", "product", False),
    ("product.tax_tax_ship", "Tax Tax Ship", "Whether tax applies to shipping costs.", "product", False),
    ("product.tax_location_id", "Tax Location Id", "Location ID for the tax rule.", "product", False),
    ("product.tax_postal_code", "Tax Postal Code", "Postal code range for the tax rule.", "product", False),
    ("product.transit_time_label", "Transit Time Label", "Label for transit time grouping.", "product", False),
    (
        "product.pickup_method",
        "Pickup Method",
        "In-store pickup option (e.g. buy, reserve, ship to store).",
        "product",
        False,
    ),
    ("product.pickup_sla", "Pickup Sla", "Expected pickup SLA (e.g. same day, next day).", "product", False),
    (
        "product.unit_pricing_measure",
        "Unit Pricing Measure",
        "Measure and dimension of the product for unit pricing.",
        "product",
        False,
    ),
    (
        "product.unit_pricing_measure_unit",
        "Unit Pricing Measure Unit",
        "Unit for the pricing measure.",
        "product",
        False,
    ),
    (
        "product.unit_pricing_base_measure",
        "Unit Pricing Base Measure",
        "Denominator for unit pricing (e.g. 100ml).",
        "product",
        False,
    ),
    (
        "product.unit_pricing_base_measure_unit",
        "Unit Pricing Base Measure Unit",
        "Unit for the base measure.",
        "product",
        False,
    ),
    (
        "product.subscription_cost_period",
        "Subscription Cost Period",
        "Billing period for subscription products.",
        "product",
        False,
    ),
    (
        "product.subscription_cost_period_length",
        "Subscription Cost Period Length",
        "Length of the subscription billing period.",
        "product",
        False,
    ),
    (
        "product.subscription_cost_period_amount",
        "Subscription Cost Period Amount",
        "Amount charged per billing period.",
        "product",
        False,
    ),
    (
        "product.subscription_cost_period_amount_currency",
        "Subscription Cost Period Amount Currency",
        "Currency of the subscription amount.",
        "product",
        False,
    ),
    (
        "product.canonical_link",
        "Canonical Link",
        "Canonical URL for the product, used to consolidate duplicate listings.",
        "product",
        False,
    ),
    (
        "product.external_seller_id_google",
        "External Seller Id Google",
        "Google-specific external seller identifier for marketplace listings.",
        "product",
        False,
    ),
    ("product.pause", "Pause", "Whether the product listing is paused.", "product", False),
    ("product.source", "Source", "Source system or feed that provided this product record.", "product", False),
    ("product.type", "Type", "Advertiser-defined product type (free-form category path).", "product", False),
    (
        "product.ads_grouping_google",
        "Ads Grouping Google",
        "Google Ads grouping label for campaign targeting.",
        "product",
        False,
    ),
    ("product.ads_redirect_google", "Ads Redirect Google", "Google Ads redirect URL for tracking.", "product", False),
    ("product.ads_labels_google", "Ads Labels Google", "Labels for Google Ads campaign targeting.", "product", False),
    (
        "product.display_ads_id_google",
        "Display Ads Id Google",
        "Product ID used in Google Display Ads.",
        "product",
        False,
    ),
    (
        "product.display_ads_title_google",
        "Display Ads Title Google",
        "Title used in Google Display Ads.",
        "product",
        False,
    ),
    (
        "product.display_ads_link_google",
        "Display Ads Link Google",
        "Landing page URL for Google Display Ads.",
        "product",
        False,
    ),
    (
        "product.display_ads_value_google",
        "Display Ads Value Google",
        "Value used for Google Display Ads conversion optimisation.",
        "product",
        False,
    ),
    (
        "product.display_ads_similar_ids_google",
        "Display Ads Similar Ids Google",
        "Similar product IDs for Google Display Ads recommendations.",
        "product",
        False,
    ),
    (
        "product.sell_on_google_quantity",
        "Sell On Google Quantity",
        "Quantity available for sale directly on Google.",
        "product",
        False,
    ),
    (
        "product.max_handling_time",
        "Max Handling Time",
        "Maximum days to prepare the product for shipping.",
        "product",
        False,
    ),
    (
        "product.min_handling_time",
        "Min Handling Time",
        "Minimum days to prepare the product for shipping.",
        "product",
        False,
    ),
    ("product.cogs", "Cogs", "Cost of goods sold — used for profit reporting.", "product", False),
    ("product.cogs_currency", "Cogs Currency", "Currency of the cost of goods sold.", "product", False),
    (
        "product.shopping_ads_excluded_country",
        "Shopping Ads Excluded Country",
        "Countries excluded from Shopping Ads for this product.",
        "product",
        False,
    ),
    ("product.promotion_ids", "Promotion Ids", "Promotion IDs associated with this product.", "product", False),
    (
        "product.included_destinations",
        "Included Destinations",
        "Ad destinations where this product should appear.",
        "product",
        False,
    ),
    (
        "product.excluded_destinations",
        "Excluded Destinations",
        "Ad destinations where this product should not appear.",
        "product",
        False,
    ),
    (
        "product.custom_lable_0",
        "Custom Lable 0",
        "Custom label 0 for Shopping campaign segmentation.",
        "product",
        False,
    ),
    (
        "product.custom_lable_1",
        "Custom Lable 1",
        "Custom label 1 for Shopping campaign segmentation.",
        "product",
        False,
    ),
    (
        "product.custom_lable_2",
        "Custom Lable 2",
        "Custom label 2 for Shopping campaign segmentation.",
        "product",
        False,
    ),
    (
        "product.custom_lable_3",
        "Custom Lable 3",
        "Custom label 3 for Shopping campaign segmentation.",
        "product",
        False,
    ),
    (
        "product.custom_lable_4",
        "Custom Lable 4",
        "Custom label 4 for Shopping campaign segmentation.",
        "product",
        False,
    ),
    (
        "product.custom_attribute_name_1",
        "Custom Attribute Name 1",
        "Name of a custom product attribute.",
        "product",
        False,
    ),
    (
        "product.custom_attribute_value_1",
        "Custom Attribute Value 1",
        "Value of a custom product attribute.",
        "product",
        False,
    ),
    (
        "product.detail_attribute_name",
        "Detail Attribute Name",
        "Name of a product detail attribute.",
        "product",
        False,
    ),
    (
        "product.detail_attribute_value",
        "Detail Attribute Value",
        "Value of a product detail attribute.",
        "product",
        False,
    ),
    ("product.highlight", "Highlight", "Key selling point or highlight for the product.", "product", False),
    (
        "product.cloud_export_additional_properties_property_name",
        "Cloud Export Additional Properties Property Name",
        "Property name for cloud export additional attributes.",
        "product",
        False,
    ),
    (
        "product.cloud_export_additional_properties_text_value",
        "Cloud Export Additional Properties Text Value",
        "Text value for cloud export additional attributes.",
        "product",
        False,
    ),
    (
        "product.cloud_export_additional_properties_bool_value",
        "Cloud Export Additional Properties Bool Value",
        "Boolean value for cloud export additional attributes.",
        "product",
        False,
    ),
    (
        "product.cloud_export_additional_properties_int_value",
        "Cloud Export Additional Properties Int Value",
        "Integer value for cloud export additional attributes.",
        "product",
        False,
    ),
    (
        "product.cloud_export_additional_properties_float_value",
        "Cloud Export Additional Properties Float Value",
        "Float value for cloud export additional attributes.",
        "product",
        False,
    ),
    (
        "product.cloud_export_additional_properties_min_value",
        "Cloud Export Additional Properties Min Value",
        "Minimum value for cloud export additional attributes.",
        "product",
        False,
    ),
    (
        "product.cloud_export_additional_properties_max_value",
        "Cloud Export Additional Properties Max Value",
        "Maximum value for cloud export additional attributes.",
        "product",
        False,
    ),
    (
        "product.cloud_export_additional_properties_unit_code",
        "Cloud Export Additional Properties Unit Code",
        "Unit code for cloud export additional attributes.",
        "product",
        False,
    ),
    ("product.weight_unit", "Weight Unit", "Unit of measurement for product weight.", "product", False),
    # ------------------------------------------------------------------ #
    # Standalone / consent  →  category = 'consent', is_pii = false
    # ------------------------------------------------------------------ #
    (
        "measurement_consent",
        "Measurement Consent",
        "Whether the user has consented to ad measurement (Google consent mode).",
        "consent",
        False,
    ),
    (
        "personalization_consent",
        "Personalization Consent",
        "Whether the user has consented to ad personalisation (Google consent mode).",
        "consent",
        False,
    ),
    # ------------------------------------------------------------------ #
    # Other standalones  →  category = 'event', is_pii = false
    # ------------------------------------------------------------------ #
    (
        "event_conversion_type",
        "Event Conversion Type",
        "Type of conversion event (e.g. offline, online) — used by Snapchat and similar platforms.",
        "event",
        False,
    ),
    (
        "action_source",
        "Action Source",
        "Top-level action source field (standalone form). Where the conversion action took place.",
        "event",
        False,
    ),
    (
        "uuid_c1",
        "Uuid C1",
        "Snapchat cookie 1 (sc_cookie1) used for Snapchat event matching.",
        "event",
        False,
    ),
    (
        "audience_name",
        "Audience Name",
        "Name of the custom audience this record should be added to.",
        "event",
        False,
    ),
]


def upgrade() -> None:
    """Seed canonical_field rows."""
    conn = op.get_bind()
    conn.execute(
        sa_text(
            """
            INSERT INTO canonical_field
                (canonical_key, field_label, field_hint, field_category, is_pii)
            VALUES
                (:canonical_key, :field_label, :field_hint, :field_category, :is_pii)
            ON CONFLICT (canonical_key) DO NOTHING
            """
        ),
        [
            {
                "canonical_key": row[0],
                "field_label": row[1],
                "field_hint": row[2],
                "field_category": row[3],
                "is_pii": row[4],
            }
            for row in CANONICAL_FIELDS
        ],
    )


def downgrade() -> None:
    """Remove seeded canonical_field rows."""
    conn = op.get_bind()
    keys = [row[0] for row in CANONICAL_FIELDS]
    conn.execute(
        sa_text("DELETE FROM canonical_field WHERE canonical_key = ANY(:keys)"),
        {"keys": keys},
    )
