"""Replace canonical_field table with datahash_schema.

Changes:
- Drop destination_field_mapping.canonical_key FK → canonical_field
- Drop project_field_mapping.canonical_key FK → canonical_field
- Drop canonical_field table
- Create datahash_schema table (id PK, canonical_key unique, extended fields)
- Re-add FKs on destination_field_mapping and project_field_mapping → datahash_schema.canonical_key

Revision ID: j5e6f7a8b9c0
Revises: i4d5e6f7a8b9
Create Date: 2026-06-20
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "j5e6f7a8b9c0"
down_revision: Union[str, Sequence[str], None] = "i4d5e6f7a8b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── 1. Drop FKs that point to canonical_field ────────────────────────────
    # FK names were auto-generated by SQLModel; use IF EXISTS to be safe.
    op.execute(
        """
        ALTER TABLE destination_field_mapping
        DROP CONSTRAINT IF EXISTS destination_field_mapping_canonical_key_fkey
        """
    )
    op.execute(
        """
        ALTER TABLE project_field_mapping
        DROP CONSTRAINT IF EXISTS project_field_mapping_canonical_key_fkey
        """
    )

    # ── 2. Drop old canonical_field table ────────────────────────────────────
    op.drop_table("canonical_field")

    # ── 3. Create datahash_schema ────────────────────────────────────────────
    op.create_table(
        "datahash_schema",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("canonical_key", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("display_label", sa.Text(), nullable=False),
        sa.Column("hint", sa.Text(), nullable=True),
        sa.Column("enum_values", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column("match_reason", sa.Text(), nullable=True),
        sa.Column("is_per_stage", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("allow_constant", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("accepted_sf_types", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column("is_pii", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_key", name="uq_datahash_canonical_key"),
    )
    op.create_index("ix_datahash_schema_canonical_key", "datahash_schema", ["canonical_key"])

    # ── 4. Re-add FKs pointing to datahash_schema.canonical_key ─────────────
    op.create_foreign_key(
        "fk_destination_field_mapping_canonical_key",
        "destination_field_mapping",
        "datahash_schema",
        ["canonical_key"],
        ["canonical_key"],
    )
    op.create_foreign_key(
        "fk_project_field_mapping_canonical_key",
        "project_field_mapping",
        "datahash_schema",
        ["canonical_key"],
        ["canonical_key"],
    )


def downgrade() -> None:
    # Drop new FKs
    op.drop_constraint("fk_project_field_mapping_canonical_key", "project_field_mapping", type_="foreignkey")
    op.drop_constraint("fk_destination_field_mapping_canonical_key", "destination_field_mapping", type_="foreignkey")

    # Drop datahash_schema
    op.drop_index("ix_datahash_schema_canonical_key", table_name="datahash_schema")
    op.drop_table("datahash_schema")

    # Re-create canonical_field
    op.create_table(
        "canonical_field",
        sa.Column("canonical_key", sa.Text(), nullable=False),
        sa.Column("field_label", sa.Text(), nullable=False),
        sa.Column("field_hint", sa.Text(), nullable=True),
        sa.Column("field_category", sa.Text(), nullable=False),
        sa.Column("is_pii", sa.Boolean(), nullable=False, server_default="false"),
        sa.PrimaryKeyConstraint("canonical_key"),
    )

    # Re-add original FKs
    op.create_foreign_key(
        "destination_field_mapping_canonical_key_fkey",
        "destination_field_mapping",
        "canonical_field",
        ["canonical_key"],
        ["canonical_key"],
    )
    op.create_foreign_key(
        "project_field_mapping_canonical_key_fkey",
        "project_field_mapping",
        "canonical_field",
        ["canonical_key"],
        ["canonical_key"],
    )
